### ISSUE TITLE
Add a configurable delay?

### ISSUE THREAD

**Issue by trg100** [ChexWarrior/atom-autosave-onchange#16]
First thing I noticed was that if I hesitate for a split second while typing a sentence then the file is autosaved and the trailing space removed. I resume typing but now have typo :(

**Comment by isthatcentered** [comment]
Hello Tom,
As I am not using atom anymore, the plugin is not maintained.

But you can definitely make a pull request and I'll add it :)

**Comment by ChexWarrior** [comment]
Hello trg100, a configurable delay (milliseconds) has been added in the latest verison. Thank you.
